### ISSUE TITLE
Handle JSONDecodeError

### ISSUE THREAD

**Issue by sotetsuk** [sotetsuk/json2tb#1]
```
Traceback (most recent call last):
  File "/opt/conda/bin/json2tb", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/json2tb/main.py", line 146, in main
    d = line2dict(line, args.ignore_broken_line)
  File "/opt/conda/lib/python3.7/site-packages/json2tb/main.py", line 132, in line2dict
    raise e
  File "/opt/conda/lib/python3.7/site-packages/json2tb/main.py", line 126, in line2dict
    d = json.loads(line)
  File "/opt/conda/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/conda/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 989 (char 9
```

**Comment by sotetsuk** [comment]
It's already handled ... One can specify option `--ignore-broken-line`
